name: Generate and Deploy Documentation from tes.yml file

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate documentation
        run: |
          pdoc --html --force --output-dir=docs .  # Generate HTML documentation in the 'docs' folder

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the 'build' job

    permissions:
      pages: write  # Allow writing to the Pages branch
      id-token: write  # Required to authenticate the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has repo access
          publish_dir: ./docs  # Directory containing generated HTML documentation
          publish_branch: gh-pages  # Branch to deploy the documentation
